name = "doglc-analytics-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Analytics Worker - Data Analysis and Monitoring
[env.production]
name = "doglc-analytics-production"
vars = { ENVIRONMENT = "production", WORKER_TYPE = "analytics" }

[env.staging]
name = "doglc-analytics-staging"
vars = { ENVIRONMENT = "staging", WORKER_TYPE = "analytics" }

# KV Namespaces for Analytics
[[kv_namespaces]]
binding = "ANALYTICS_CACHE_KV"
id = "analytics-cache-namespace-id"
preview_id = "analytics-cache-preview-id"

[[kv_namespaces]]
binding = "METRICS_KV"
id = "metrics-namespace-id"
preview_id = "metrics-preview-id"

[[kv_namespaces]]
binding = "PERFORMANCE_KV"
id = "performance-namespace-id"
preview_id = "performance-preview-id"

# D1 Database for analytics data
[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "doglc-analytics-db"
database_id = "analytics-database-id"

[[d1_databases]]
binding = "METRICS_DB"
database_name = "doglc-metrics-db"
database_id = "metrics-database-id"

# R2 Buckets for data storage
[[r2_buckets]]
binding = "ANALYTICS_DATA_R2"
bucket_name = "doglc-analytics-data"
preview_bucket_name = "doglc-analytics-data-preview"

[[r2_buckets]]
binding = "REPORTS_R2"
bucket_name = "doglc-reports"
preview_bucket_name = "doglc-reports-preview"

# Queue bindings for background processing
[[queues]]
binding = "ANALYTICS_QUEUE"
queue = "analytics-processing-queue"

[[queues]]
binding = "METRICS_QUEUE"
queue = "metrics-collection-queue"

# Analytics Engine for comprehensive data analysis
[[analytics_engine_datasets]]
binding = "TRANSACTION_ANALYTICS"
dataset = "transaction_data"

[[analytics_engine_datasets]]
binding = "USER_BEHAVIOR_ANALYTICS"
dataset = "user_behavior_data"

[[analytics_engine_datasets]]
binding = "SECURITY_ANALYTICS"
dataset = "security_events_data"

[[analytics_engine_datasets]]
binding = "PERFORMANCE_ANALYTICS"
dataset = "performance_metrics_data"

# Vectorize for pattern analysis
[[vectorize]]
binding = "BEHAVIOR_ANALYSIS_AI"
index_name = "user-behavior-vectors"

[[vectorize]]
binding = "PATTERN_DETECTION_AI"
index_name = "transaction-pattern-vectors"

# AI binding for advanced analytics
[ai]
binding = "AI"

# Browser rendering for report generation
[browser]
binding = "BROWSER"

# Node.js compatibility
node_compat = true

# Observability configuration
[observability]
enabled = true
head_sampling_rate = 0.1