name = "doglc-analytics-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Analytics Worker - Data Analysis and Monitoring
[env.production]
name = "doglc-analytics-production"
vars = { ENVIRONMENT = "production", WORKER_TYPE = "analytics" }

[env.staging]
name = "doglc-analytics-staging"
vars = { ENVIRONMENT = "staging", WORKER_TYPE = "analytics" }
