name = "doglc-api-v2"
main = "workers/main-bot/src/simple-api-v2.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# API v2 configuration
[vars]
ENVIRONMENT = "development"
WORKER_TYPE = "api-v2"
API_VERSION = "2.0.0"

# Production environment
[env.production]
name = "doglc-api-v2-production"
[env.production.vars]
ENVIRONMENT = "production"
WORKER_TYPE = "api-v2"
API_VERSION = "2.0.0"