name = "doglc-digital-wallet"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Enhanced Cloudflare Workers configuration with banking operations support
[env.staging]
name = "doglc-digital-wallet-staging"
vars = { ENVIRONMENT = "staging", DEBUG_MODE = "true", LOG_LEVEL = "debug" }

[env.production]
name = "doglc-digital-wallet-production" 
vars = { ENVIRONMENT = "production", DEBUG_MODE = "false", LOG_LEVEL = "info" }

# Production KV Namespaces
[[env.production.kv_namespaces]]
binding = "CONFIG_KV"
id = "31f813fdf51743a0a96a7dc22b45f22c"
preview_id = "your-preview-config-kv-id"

[[env.production.kv_namespaces]]
binding = "RATE_KV"
id = "0a3ec022e9b14774ba5791e5d5f0f6b7"
preview_id = "your-preview-rate-kv-id"

[[env.production.kv_namespaces]]
binding = "USER_SESSIONS"
id = "cfe9a09ceea142728bb949be6a165296"
preview_id = "your-preview-user-sessions-id"

[[env.production.kv_namespaces]]
binding = "MARKET_DATA_CACHE"
id = "b3df3a37e1f647c4a62d68655e452cce"
preview_id = "your-preview-market-data-cache-id"

[[env.production.kv_namespaces]]
binding = "SLIP_IMAGES"
id = "d3148c4f344249f19f32682fb5f6a8ca"
preview_id = "your-preview-slip-images-id"

[[env.production.kv_namespaces]]
binding = "AUDIT_LOG_KV"
id = "e31d487a80b442aaba15444c7982b6a0"
preview_id = "your-preview-audit-log-kv-id"

[[env.production.kv_namespaces]]
binding = "USER_ACTIVITY_KV"
id = "4582f3e06c6a42f6b48afdffde6c750d"
preview_id = "user-activity-store-preview-id"

[[env.production.kv_namespaces]]
binding = "PERFORMANCE_KV"
id = "4d36a18049f044ff80e595b962a74b31"
preview_id = "performance-metrics-store-preview-id"

[[env.production.kv_namespaces]]
binding = "OCR_LOG_KV"
id = "bed0205ccfd94275b5f21ed18d2a9920"
preview_id = "ocr-processing-log-store-preview-id"

[[env.production.kv_namespaces]]
binding = "GMAIL_LOG_KV"
id = "9571bdf53290445f9e480aeababb6b08"
preview_id = "gmail-webhook-log-store-preview-id"

[[env.production.kv_namespaces]]
binding = "DEPOSIT_REQUESTS_KV"
id = "74657733c0004630b1f8a00019531d75"
preview_id = "deposit-requests-store-preview-id"

[[env.production.kv_namespaces]]
binding = "CONFIRMED_DEPOSITS_KV"
id = "7f4a4b7fb36144a38813002cc43c3913"
preview_id = "confirmed-deposits-store-preview-id"

[[env.production.kv_namespaces]]
binding = "SECURITY_EVENTS_KV"
id = "edf24ceaf0a84eeca9f3314ff88b70ad"
preview_id = "security-events-store-preview-id"

# Production D1 Databases
[[env.production.d1_databases]]
binding = "WALLET_DB"
database_name = "doglc-wallet-db"
database_id = "c5d8abef-1763-4c6a-afb4-00a77a8e412c"

[[env.production.d1_databases]]
binding = "ANALYTICS_DB"
database_name = "doglc-analytics-db"
database_id = "e4e62d0b-06d3-4033-9550-107632bbd3b7"

[[env.production.d1_databases]]
binding = "DOGLC_DB"
database_name = "doglc-main-db"
database_id = "73765794-dbf9-4561-82d2-b4f2d2912947"

# Enhanced KV Namespaces for comprehensive functionality
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "31f813fdf51743a0a96a7dc22b45f22c"
preview_id = "your-preview-config-kv-id"

[[kv_namespaces]]
binding = "RATE_KV"
id = "0a3ec022e9b14774ba5791e5d5f0f6b7"
preview_id = "your-preview-rate-kv-id"

[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "cfe9a09ceea142728bb949be6a165296"
preview_id = "your-preview-user-sessions-id"

[[kv_namespaces]]
binding = "MARKET_DATA_CACHE"
id = "b3df3a37e1f647c4a62d68655e452cce"
preview_id = "your-preview-market-data-cache-id"

[[kv_namespaces]]
binding = "SLIP_IMAGES"
id = "d3148c4f344249f19f32682fb5f6a8ca"
preview_id = "your-preview-slip-images-id"

[[kv_namespaces]]
binding = "AUDIT_LOG_KV"
id = "e31d487a80b442aaba15444c7982b6a0"
preview_id = "your-preview-audit-log-kv-id"

# Enhanced KV for advanced features
[[kv_namespaces]]
binding = "USER_ACTIVITY_KV"
id = "4582f3e06c6a42f6b48afdffde6c750d"
preview_id = "user-activity-store-preview-id"

[[kv_namespaces]]
binding = "PERFORMANCE_KV"
id = "4d36a18049f044ff80e595b962a74b31"
preview_id = "performance-metrics-store-preview-id"

[[kv_namespaces]]
binding = "OCR_LOG_KV"
id = "bed0205ccfd94275b5f21ed18d2a9920"
preview_id = "ocr-processing-log-store-preview-id"

[[kv_namespaces]]
binding = "GMAIL_LOG_KV"
id = "9571bdf53290445f9e480aeababb6b08"
preview_id = "gmail-webhook-log-store-preview-id"

[[kv_namespaces]]
binding = "DEPOSIT_REQUESTS_KV"
id = "74657733c0004630b1f8a00019531d75"
preview_id = "deposit-requests-store-preview-id"

[[kv_namespaces]]
binding = "CONFIRMED_DEPOSITS_KV"
id = "7f4a4b7fb36144a38813002cc43c3913"
preview_id = "confirmed-deposits-store-preview-id"

[[kv_namespaces]]
binding = "SECURITY_EVENTS_KV"
id = "edf24ceaf0a84eeca9f3314ff88b70ad"
preview_id = "security-events-store-preview-id"

# Enhanced D1 databases for comprehensive data management
[[d1_databases]]
binding = "WALLET_DB"
database_name = "doglc-wallet-db"
database_id = "c5d8abef-1763-4c6a-afb4-00a77a8e412c"

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "doglc-analytics-db"
database_id = "e4e62d0b-06d3-4033-9550-107632bbd3b7"

[[d1_databases]]
binding = "DOGLC_DB"
database_name = "doglc-main-db"
database_id = "73765794-dbf9-4561-82d2-b4f2d2912947"

# Enhanced R2 buckets for file storage and backups
[[r2_buckets]]
binding = "WALLET_BUCKET"
bucket_name = "doglc-wallet-bucket"

[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "doglc-backup-bucket"

[[r2_buckets]]
binding = "SLIP_IMAGES_R2"
bucket_name = "doglc-slip-images"

[[r2_buckets]]
binding = "IMAGES_R2"
bucket_name = "doglc-images"

[[r2_buckets]]
binding = "RECEIPTS_R2"
bucket_name = "doglc-receipts"

[[r2_buckets]]
binding = "REPORTS_R2"
bucket_name = "doglc-reports"

# Documents bucket - create later
# [[r2_buckets]]
# binding = "DOCUMENTS_R2"
# bucket_name = "doglc-documents"

# Durable Objects for real-time features and state management (coming soon)
# [[durable_objects.bindings]]
# name = "WALLET_DO"
# class_name = "WalletDurableObject"

# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiterDurableObject"

# [[durable_objects.bindings]]
# name = "USER_SESSION_MANAGER"
# class_name = "UserSessionManager"

# Enhanced Service bindings for multi-worker architecture (staging environment)
[[services]]
binding = "BANKING_WORKER"
service = "doglc-banking-worker-staging"

[[services]]
binding = "SECURITY_WORKER"
service = "doglc-security-worker-staging"

[[services]]
binding = "FRONTEND_WORKER"
service = "doglc-frontend-worker-staging"

[[services]]
binding = "ANALYTICS_WORKER"
service = "doglc-analytics-worker-staging"

[[services]]
binding = "API_WORKER"
service = "doglc-api-worker-staging"

# Queue bindings for background processing (coming soon)
# [[queues.producers]]
# binding = "DEPOSIT_QUEUE"
# queue = "deposit-processing-queue"

# [[queues.producers]]
# binding = "WITHDRAWAL_QUEUE"
# queue = "withdrawal-processing-queue"

# [[queues.producers]]
# binding = "NOTIFICATION_QUEUE"
# queue = "notification-queue"

# [[queues.producers]]
# binding = "OCR_QUEUE"
# queue = "ocr-processing-queue"

# [[queues.producers]]
# binding = "GMAIL_QUEUE"
# queue = "gmail-webhook-queue"

# Vectorize for AI/ML features (coming soon)
# [[vectorize]]
# binding = "FRAUD_DETECTION_AI"
# index_name = "fraud-detection-vectors"

# [[vectorize]]
# binding = "OCR_AI_VECTORS"
# index_name = "ocr-pattern-vectors"

# Analytics Engine for comprehensive data analysis (coming soon)
# [[analytics_engine_datasets]]
# binding = "TRANSACTION_ANALYTICS"
# dataset = "transaction_data"

# [[analytics_engine_datasets]]
# binding = "USER_BEHAVIOR_ANALYTICS"
# dataset = "user_behavior_data"

# [[analytics_engine_datasets]]
# binding = "SECURITY_ANALYTICS"
# dataset = "security_events_data"

# Email configuration for notifications (coming soon)
# [email]
# binding = "EMAIL"
# destination_address = "support@doglc.digital"

# Hyperdrive for database acceleration (coming soon)
# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = "your-hyperdrive-config-id"

# AI binding for enhanced fraud detection (coming soon)
# [ai]
# binding = "AI"

# Placement configuration for optimal performance
[placement]
mode = "smart"

# Node.js compatibility for crypto and other modules
node_compat = true

# Workers limits and pricing tier
[limits]
cpu_ms = 30000  # 30 seconds max execution time

# Asset configuration for static files
# [[migrations]]
# tag = "v1"
# new_classes = ["WalletDurableObject", "RateLimiterDurableObject", "UserSessionManager"]

[assets]
directory = "./public"
binding = "ASSETS"

# Observability configuration
[observability]
enabled = true
head_sampling_rate = 0.01