name = "doglc-frontend-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Development environment variables
[vars]
ENVIRONMENT = "development"
WORKER_TYPE = "frontend"
MAIN_BOT_URL = "http://localhost:8788"

# Production environment
[env.production]
name = "doglc-frontend-production"
[env.production.vars]
ENVIRONMENT = "production"
WORKER_TYPE = "frontend"
MAIN_BOT_URL = "https://doglc-main-bot.your-worker.workers.dev"
ALLOWED_ORIGINS = "https://web.telegram.org"

# Staging environment
[env.staging]
name = "doglc-frontend-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
WORKER_TYPE = "frontend"
MAIN_BOT_URL = "https://doglc-main-bot-staging.your-worker.workers.dev"
ALLOWED_ORIGINS = "https://web.telegram.org,http://localhost:8787"