name = "doglc-banking-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Banking Worker - Financial Operations
[env.production]
name = "doglc-banking-production"
vars = { ENVIRONMENT = "production", WORKER_TYPE = "banking" }

[env.staging]
name = "doglc-banking-staging"
vars = { ENVIRONMENT = "staging", WORKER_TYPE = "banking" }

# D1 Databases for Banking Operations
[[d1_databases]]
binding = "MAIN_WALLET_DB"
database_name = "doglc-wallet-main"
database_id = "49747ab5-7e7f-4c70-abf3-84f099354cf7"

[[d1_databases]]
binding = "BANKING_SYSTEM_DB"
database_name = "doglc-banking-system"
database_id = "abb80d11-b1c1-499b-88d3-3df2ebbb5525"

# Node.js compatibility
node_compat = true