name = "doglc-api-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# API Worker - RESTful Services
[env.production]
name = "doglc-api-production"
vars = { ENVIRONMENT = "production", WORKER_TYPE = "api" }

[env.staging]
name = "doglc-api-staging"
vars = { ENVIRONMENT = "staging", WORKER_TYPE = "api" }

