name = "doglc-security-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Security Worker - OCR and Security Operations
[env.production]
name = "doglc-security-production"
vars = { 
  ENVIRONMENT = "production", 
  WORKER_TYPE = "security",
  OCR_PROCESSING_TIMEOUT = "30000",
  VERIFICATION_CONFIDENCE_THRESHOLD = "0.7",
  EMAIL_PROCESSING_ENABLED = "true",
  GMAIL_WEBHOOK_ENABLED = "true",
  FRAUD_DETECTION_ENABLED = "true"
}

[env.staging]
name = "doglc-security-staging"
vars = { 
  ENVIRONMENT = "staging", 
  WORKER_TYPE = "security",
  OCR_PROCESSING_TIMEOUT = "15000",
  VERIFICATION_CONFIDENCE_THRESHOLD = "0.6"
}

# D1 Database for Security Operations
[[d1_databases]]
binding = "MAIN_WALLET_DB"
database_name = "doglc-wallet-main"
database_id = "49747ab5-7e7f-4c70-abf3-84f099354cf7"

# KV Namespaces for Security Operations (Production IDs)
[[kv_namespaces]]
binding = "SECURITY_TOKENS"
id = "edf24ceaf0a84eeca9f3314ff88b70ad"
preview_id = "edf24ceaf0a84eeca9f3314ff88b70ad"

[[kv_namespaces]]
binding = "SLIP_IMAGES"
id = "d3148c4f344249f19f32682fb5f6a8ca"
preview_id = "d3148c4f344249f19f32682fb5f6a8ca"

[[kv_namespaces]]
binding = "SLIP_IMAGES_METADATA"
id = "7dd86eee2ed241fca77d165310f54fb6"
preview_id = "7dd86eee2ed241fca77d165310f54fb6"

[[kv_namespaces]]
binding = "DOGLC_LOGS"
id = "b3f14c9db2bd4c1a9f075561afb8deca"
preview_id = "b3f14c9db2bd4c1a9f075561afb8deca"

[[kv_namespaces]]
binding = "AUDIT_LOG_KV"
id = "audit-log-namespace-id"
preview_id = "audit-log-preview-id"

# D1 Database for security logs
[[d1_databases]]
binding = "SECURITY_DB"
database_name = "doglc-security-db"
database_id = "security-database-id"

# R2 Buckets for OCR processing
[[r2_buckets]]
binding = "OCR_STORAGE_R2"
bucket_name = "doglc-ocr-storage"
preview_bucket_name = "doglc-ocr-storage-preview"

[[r2_buckets]]
binding = "DOCUMENTS_R2"
bucket_name = "doglc-documents"
preview_bucket_name = "doglc-documents-preview"

# Queue bindings for OCR processing
[[queues]]
binding = "OCR_QUEUE"
queue = "ocr-processing-queue"

[[queues]]
binding = "GMAIL_QUEUE"
queue = "gmail-webhook-queue"

[[queues]]
binding = "SECURITY_QUEUE"
queue = "security-events-queue"

# Vectorize for AI fraud detection
[[vectorize]]
binding = "FRAUD_DETECTION_AI"
index_name = "fraud-detection-vectors"

[[vectorize]]
binding = "OCR_AI_VECTORS"
index_name = "ocr-pattern-vectors"

# AI binding for enhanced processing
[ai]
binding = "AI"

# Service bindings
[[services]]
binding = "ANALYTICS_WORKER"
service = "doglc-analytics-worker"

# Node.js compatibility
node_compat = true