name = "doglc-security-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Security Worker - OCR and Security Operations
[env.production]
name = "doglc-security-production"
vars = { ENVIRONMENT = "production", WORKER_TYPE = "security" }

[env.staging]
name = "doglc-security-staging"
vars = { ENVIRONMENT = "staging", WORKER_TYPE = "security" }
# ไม่ต้องมี node_compat แล้ว ใช้ compatibility_flags = ["nodejs_compat"] แทน